### PR TITLE
All basic stuffs

### PR DESCRIPTION
**Pull request by devil-black-786**

### CODE REVIEW

**Comment by blacklytning** [comment]
Remove AOD as well as fps overlay.

**Comment by devil-black-786** [comment]
@blacklytning neboor

**Comment by blacklytning** [comment]
@devil-black-786 dont worry then i will close myself close this pr

**Comment by ghostmirrorlab** [comment]
aod is lob even thou i have lcd display xD

**Comment by blacklytning** [comment]
@devil-black-786 send 10k mah power bank with the commit

**Comment by devil-black-786** [comment]
Anime lob

**Comment by kardebayan** [comment]
@devil-black-786 anime gay

**Comment by ghostmirrorlab** [comment]
anime is lob man

**Comment by ghostmirrorlab** [comment]
i love sakura

**Comment by blacklytning** [comment]
> i love sakura

Gomi wa gomi ga suki

**Comment by ghostmirrorlab** [comment]
> > i love sakura
> 
> Gomi wa gomi ga suki

ayyy u shut up sakura is lob

**Comment by CyberJalagam** [comment]
hi

**Comment by kardebayan** [comment]
@CyberJalagam Hello

**Comment by CyberJalagam** [comment]
> @CyberJalagam Hello

ok

**Comment by kardebayan** [comment]
@CyberJalagam Ok

**Comment by ghostmirrorlab** [comment]
ok

**Pull request closed without merging**
